#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

add-apt-repository ppa:deadsnakes/ppa

apt-get update

apt-get install --yes\
    python3.7 python3.7-dev python3.7-venv\
    python3.8 python3.8-dev python3.8-venv\
    python3.9 python3.9-dev python3.9-venv

rm -rf /var/lib/apt/lists/*
