# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import torch

def enter_deferred_init() -> None: ...
def leave_deferred_init() -> None: ...
def enter_fake_mode(fake_mode: bool) -> None: ...
def leave_fake_mode() -> None: ...
def is_fake(tensor: torch.Tensor) -> bool: ...
def materialize_tensor(tensor: torch.Tensor) -> torch.Tensor: ...
def meta_like(fake: torch.Tensor) -> torch.Tensor: ...
