# Copyright (c) Meta Platforms, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import torch

def enable_deferred_init(value: bool) -> None: ...
def enable_fake_mode(value: bool) -> None: ...
def is_fake(tensor: torch.Tensor) -> bool: ...
def materialize_tensor(tensor: torch.Tensor) -> torch.Tensor: ...
