#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

yum --assumeyes install\
    devtoolset-9-gcc\
    devtoolset-9-gcc-c++\
    devtoolset-9-libasan-devel\
    devtoolset-9-liblsan-devel\
    devtoolset-9-libubsan-devel\
    devtoolset-9-libtsan-devel

yum clean all
